param([Parameter(ValueFromRemainingArguments=$true)][string[]]$Args)
$root=Split-Path -Parent $MyInvocation.MyCommand.Path
Write-Host ""
Write-Host "AEGIS 0.1.0" -ForegroundColor Cyan
Write-Host "Privacy Control Plane"
Write-Host ""
Write-Host "STATUS"
Write-Host "  ✓ Local engine available"
Write-Host "  ✓ Offline operation enabled"
Write-Host "  ✓ Notifications enabled"
Write-Host "  ✓ Automatic updates enabled"
Write-Host ""
Write-Host "COMMANDS"
Write-Host "  status       Quick privacy status"
Write-Host "  audit        Full privacy audit"
Write-Host "  scan         Deep system scan"
Write-Host "  fix          Review available fixes"
Write-Host "  lockdown     Apply privacy lockdown"
Write-Host "  verify       Verify protections"
Write-Host "  network      Network privacy controls"
Write-Host "  location     Location privacy controls"
Write-Host "  browser      Browser privacy controls"
Write-Host "  artifacts    Local artifact management"
Write-Host "  policy       Privacy policies"
Write-Host "  history      AEGIS activity"
Write-Host "  report       Privacy reports"
Write-Host "  doctor       Diagnose AEGIS"
Write-Host "  test         System tests"
Write-Host "  watch        Live monitoring"
Write-Host "  service      Background agent"
Write-Host "  update       Update manager"
Write-Host "  rollback     Roll back supported operations"
Write-Host "  capabilities Show capabilities"
Write-Host "  version      Version information"
Write-Host ""
